export const EntityNames = {
    GUN_AK47: 'gunAk47',
    GUN_P90: 'gunP90',
    GUN_FN_SCAR: 'gunFn-scar',
    GUN_MP5: 'gunMp5',
    GUN_MP7: 'gunMp7',
    GUN_MP10: 'gunMp10',
    GUN_M4: 'gunM4',
    GUN_RPG: 'gunRPG',
    GUN_REMINGTON870: 'gunRemington870',
    GUN_CDP12: 'gunCdp12',
    AMMO_SMALL: 'ammoSmall',
    AMMO_NORMAL: 'ammoNormal',
    AMMO_LARGE: 'ammoLarge',
    AMMO_ROCKET: 'ammoRocket',
    AMMO_GRENADE: 'ammoGrenade',
    AMMO_SHOTGUN: 'ammoShotgun',
    AMMO_SNIPER: 'ammoSniper',
    AMMO_NORMAL: 'ammoNormal',
}

export const SpriteMap = {
    [EntityNames.GUN_AK47]: [],
    [EntityNames.GUN_P90]: [],
    [EntityNames.GUN_FN_SCAR]: [],
    [EntityNames.GUN_MP5]: [],
    [EntityNames.GUN_MP7]: [],
    [EntityNames.GUN_MP10]: [],
    [EntityNames.GUN_M4]: [],
    [EntityNames.GUN_RPG]: [],
    [EntityNames.GUN_REMINGTON870]: [],
    [EntityNames.GUN_CDP12]: [],
    [EntityNames.GUN_CDP12]: [],
    [EntityNames.AMMO_SMALL]: [105, 8, 15, 18],
    [EntityNames.AMMO_NORMAL]: [9, 8, 15, 18],
    [EntityNames.AMMO_LARGE]: [133, 5, 23, 26],
    [EntityNames.AMMO_ROCKET]: [],
    [EntityNames.AMMO_GRENADE]: [],
    [EntityNames.AMMO_SHOTGUN]: [37, 5, 22, 23],
    [EntityNames.AMMO_SNIPER]: [69, 4, 21, 25],
    [EntityNames.AMMO_NORMAL]: [],
}